Change ModuleGroupMap to ModuleSet
AY2122S1-CS2103-W14-3/tp pull request #192
Opened 2021-11-01 03:58 UTC by FergusMok

This will allow a person's module to have multiple groups (Labs, Tutorials, Lecture etc..) instead of only having 1.

2021-11-05 19:09 UTC, chaiwanlin requested changes
Just a small suggestion, otherwise lgtm

2021-11-05 19:09 UTC, chaiwanlin commented on src/main/java/seedu/edrecord/model/module/ModuleSet.java
> +            }
```suggestion
            if (module.getCode().equals(mod.getCode()) && module.hasGroup(grp)) {
                return true;
            }
```
Less arrow-head style code

2021-11-06 09:15 UTC, marcusc55 approved these changes
LGTM

2021-11-06 10:54 UTC, chaiwanlin approved these changes
lgtm

2021-11-06 12:27 UTC, merged